---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vibe-job-lp/ks.yaml
#  - ./invidious/ks.yaml
  - ./sonarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./split-pro/ks.yaml
  - ./sparkyfitness/ks.yaml
  - ./mealie/ks.yaml
  - ./home-assistant/ks.yaml