---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "internal-pool"
spec:
  blocks:
  - start: "192.168.67.1"
    stop: "192.168.67.62"
  - start: "10.11.0.5"
    stop: "10.11.0.8"
  serviceSelector:     
    matchExpressions:
      - { key: bgp, operator: In, values: [ internal ] }