---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium-bgp-advertisement.yaml
  - ./cilium-bgp-peerconfig.yaml
  - ./cilium-bgp-clusterconfig.yaml
  - ./cilium-l2-public.yaml  
  - ./internal-pool.yaml
  - ./public-pool.yaml