---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tuppr-controller
  namespace: &namespace system-upgrade
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/galaxy-cluster/kubernetes/apps/system-upgrade/tuppr/app
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tuppr-controller
      namespace: system-upgrade
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tuppr-upgrades
  namespace: &namespace system-upgrade
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/galaxy-cluster/kubernetes/apps/system-upgrade/tuppr/upgrades
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: tuppr-controller
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      # renovate: depName=ghcr.io/siderolabs/installer datasource=docker
      TALOS_VERSION: v1.10.7
      # renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
      KUBERNETES_VERSION: v1.33.4