ports:
  dns: 53
  http: 4000

upstreams:
  init:
    strategy: fast
  groups:
    default:
      - https://dns.quad9.net/dns-query
      - https://dns.digitale-gesellschaft.ch/dns-query
      - 208.67.222.123
      - 1.1.1.1

bootstrapDns:
  - tcp+udp:1.1.1.1
  - tcp+udp:8.8.8.8

# Add needed queries
customDNS:
  customTTL: 1h
  mapping:
    lldap.de.plutode.com: 192.168.67.12
    grafana.de.plutode.com: 192.168.67.12
    alertmanager.de.plutode.com: 192.168.67.12
    prometheus.de.plutode.com: 192.168.67.12
    temp.ha.de.plutode.com: 192.168.67.12
    ha.de.plutode.com: 192.168.67.12
    split.de.plutode.com: 192.168.67.12
    auth.de.plutode.com: 192.168.67.12
    a.de.plutode.com: 192.168.67.12
    mqtt.de.plutode.com: 10.11.0.111
    jellyfin.de.plutode.com: 10.21.0.31
    mealie.de.plutode.com: 192.168.67.12
    nas.de.plutode.com: 10.21.0.31
    request.de.plutode.com: 192.168.67.12
    sonarr.de.plutode.com: 192.168.67.12
    prowlarr.de.plutode.com: 192.168.67.12
    radarr.de.plutode.com: 192.168.67.12
    youtube.de.plutode.com: 192.168.67.12
    fitness.de.plutode.com: 192.168.67.12

# Split dns
conditional:
  fallbackUpstream: false
  mapping:
    nl.plutode.com: 192.168.10.11
    lu.plutode.com: 192.168.13.69
    hvb.plutode.com: 192.168.1.76

blocking:
  denylists:
    general:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/multi.txt

  clientGroupsBlock:
    default:
      - general

